### ISSUE TITLE
[BUG] Trying to change from epiccash to another crypto, sending to changenow address does not work

### ISSUE THREAD

**Issue by claude-elwood-shannon** [EpicCash/epic-wallet#113]
**Send using changnow does not work**
When trying to change from epiccash to another crypto, sending does not work.

**To Reproduce**
Using the following command;
epic-wallet -p mypasswordwallet -d https://epic.changenow.io/########## -m epicbox amount

Give the following output;
Wallet command failed: LibWallet Error: "LibWallet Error"

**Expected behavior**
The amount should be sent and the changenow operation should finish succeeded.

**Required data**
 - epic-wallet 3.6.0
 - The changenow address

**Additional context**
The wallet was previously used to send to other parties.

**Comment by who-biz** [comment]
Hi - please report this in Support channels.  We have no control over exchanges, and this is an issue tracker for technical issues.

**Comment by who-biz** [comment]
Will reopen if there are relevant logs you have, that suggest this is not an issue with ChangeNow.
