### ISSUE TITLE
Wallet Tx Details lost Output/s

### ISSUE THREAD

**Issue by johanneshahn** [EpicCash/epic-wallet#26]
The Wallet DB lost the outputs in its details and via API calls.

If user receive a transaction and watch the details or calls this tx details from api he will get a list from the outputs for this transaction.
![receive_detail](https://user-images.githubusercontent.com/1593652/163038029-03a82152-4bb9-4fe1-a67d-18a47bf0ce98.png)

If user then creates a new send transaction and use the output he previously receveived from the receive transaction,
then the list from the outputs is empty.
![receive_detail2](https://user-images.githubusercontent.com/1593652/163038395-5e67719c-81d9-4f00-8bef-e468886d29c3.png)

Details of users new send transaction with the output he receives previously (new tx id is now 73)
![receveive_detail3](https://user-images.githubusercontent.com/1593652/163038537-6f80e1d1-c9da-4054-b55a-a3095ff6af5f.png)

The Details for the outputs is not shown, because the tx id of the output is changed if users creates a new transaction.
The new tx id can not be assigned to older transactions. A history is missing

**Comment by backendbox** [comment]
Same here

**Comment by MarcioMacedoBA** [comment]
**Describe the bug**

Some details of the wallet output are lost after transactions.

**To reproduce**

This issue can be easily reproduced on `usernet` as follows:
- Start the server: `epic --usernet`;
- Create three empty wallets (here named A, B, C): `epic-wallet --usernet init`
- Mine some coins for wallet A: `epic-wallet --usernet listen`
- Send C coins from wallet A to wallet B (via `send` command): `epic-wallet --usernet send -m file -d 'temp.txt' -s smallest C`
- Receive C coins from wallet B (via `receive` command): `epic-wallet --usernet receive -i 'temp.txt'`
- Finalize the transaction from wallet A (via `finalize` command); `epic-wallet --usernet finalize -i 'temp.txt.reponse'`
- Mine 10 blocks to validate the transaction (you can put wallet A on `listen` mode to allow the mining): `epic-wallet --usernet listen`
- Print the taxes and outputs of wallet B to confirm the receipt of the C coins (`txs` and `outputs` commands): 
    - `epic-wallet --usernet txs`
    - `epic-wallet --usernet outputs`
- Send C coins from wallet B to wallet C (via `send` command): `epic-wallet --usernet send -m file -d "temp.txt" -s smallest <C-fee>`
- Receive C coins from wallet C (via `receive` command): `epic-wallet --usernet receive -i 'temp.txt'`
- Print the taxes and outputs of wallet B to confirm the sending of the C coins (`txs` and `outputs` commands);
    - `txs` prints the correct information and assignes the `send` command to a new transaction id;
    - `outputs` contains the sending of the C coins, but pointing to the id of the most recent transaction (the old transaction id is lost);

**Comment by MarcioMacedoBA** [comment]
@johanneshahn I am in doubt about what should be the expected behaviour in this case. Should the `outputs` command print the list of transaction ids (one per `outputs line, for instance) that are associated with a given output, and the user could then trace, or better investigate their relation through the use of the `txs` command?
