### ISSUE TITLE
[BUG] Wallet Fails on Load Under Ubuntu 22.04

### ISSUE THREAD

**Issue by skykingisepic** [EpicCash/epic-wallet#53]
Wallet Fails to load on Ubuntu 22.04

2023-02-11 12:44:45:078 [info]  execStart.stderr /tmp/.mount_EpicWav1VIBT/resources/bin/linux/epic-wallet: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

Ubuntu 22.04 upgraded to OpenSSL 3.0 so OpenSSL 1.1 depricated in Ubuntu 22.04 and not providing libssl.so.1.1

**Comment by KeithZR** [comment]
I am getting this same error under debian 12

**Comment by who-biz** [comment]
Closing due to long-standing issue, and well-known at this point.

**Comment by who-biz** [comment]
For anyone who comes upon this later: 

Binaries compiled on Ubuntu 20.04 will run on Ubuntu 20.04 only.
Binaries compiled on Ubuntu 22.04 will run on Ubuntu 22.04 only.

This is due to breaking changes in OpenSSL.  Expect these issues to continue until (and if) 20.04 gets the bump up to OpenSSL v3

**Comment by sang-shelton** [comment]
I cannot find libssl1 in my repos, all i can find and have in the system in libssl3.
Is there a fix to that ?
