### ISSUE TITLE
[FEATURE REQUEST] Adjustable Epicbox Subscription Refresh

### ISSUE THREAD

**Issue by skykingisepic** [EpicCash/epic-wallet#54]
Allow changing Subscription Refresh cycle time with a minimum of no less than 15 sec to avoid dDoS attack like behavior and a maximum of no more than 3 minutes or it becomes pointless as transaction times become too long. -r 30, REFRESH=15, etc.

**Comment by blacktyger** [comment]
Added here: https://github.com/EpicCash/epic-wallet/pull/56
