### ISSUE TITLE
[FEATURE] Display full epicbox address

### ISSUE THREAD

**Issue by blacktyger** [EpicCash/epic-wallet#74]
When `epic-wallet address` command used display full epicbox address with domain:

`esYeNScdKxUbm...sZPLDKM1eCsBmhF@epicbox.epic.tech`

Now only public key part is displayed and this is not enough for sender to successfully send the transaction via epicbox.

**Comment by stylian70** [comment]
... and it is called "Address for account".

Improvement: see above and increase verbosity to "Epicbox public address for account"

In a very related matter: The "address" subcommand help comment says "Display the wallet's payment proof address", i.e. it does not mention the epicbox address (nor the TOR address btw).

Improvement to help comment: "Display the wallet's Epicbox public address, the payment proof address and the TOR address"
